-- Run in Supabase SQL Editor to add vehicle category support for existing databases.
alter table public.requests
  add column if not exists vehicle_category text not null default 'car';

alter table public.requests drop constraint if exists requests_vehicle_category_check;

alter table public.requests add constraint requests_vehicle_category_check
  check (vehicle_category in ('car', 'van'));

create index if not exists requests_vehicle_category_idx
  on public.requests (vehicle_category);

insert into public.requests (
  id,
  status,
  vehicle_category,
  vehicle_name,
  vehicle_title,
  service,
  license_plate,
  distance_km,
  location_city,
  vin,
  engine_volume,
  power,
  fuel_type,
  year,
  engine,
  drive,
  body_type,
  doors,
  mileage_km,
  transmission,
  inquiry_description,
  user_name,
  phone
) values
  (
    '13',
    'inquiry',
    'van',
    'Ford Transit',
    'Ford Transit 2.0 TDCi',
    'Výmena oleja a filtrov',
    'ZA331DT',
    19.4,
    'Žilina',
    'WF0XXXTTGX1234567',
    '2.0 l',
    '96 kW',
    'Diesel',
    2018,
    '2.0 TDCi',
    'FWD',
    'Dodávka',
    4,
    214800,
    'Manuálna',
    'Potrebujem servisnú výmenu oleja a filtrov pred dlhšou trasou po Slovensku.',
    'Martin Ďurica',
    '+421 910 441 220'
  ),
  (
    '14',
    'inquiry',
    'van',
    'Mercedes Sprinter',
    'Mercedes Sprinter 316 CDI',
    'Kontrola bŕzd',
    'NO552SP',
    37.2,
    'Dolný Kubín',
    'WDB9066331S123456',
    '2.1 l',
    '120 kW',
    'Diesel',
    2016,
    '316 CDI',
    'RWD',
    'Dodávka',
    4,
    289400,
    'Manuálna',
    'Pri plnom zaťažení cítim slabšie brzdenie, prosím o kontrolu brzdového systému.',
    'Jozef Kmeť',
    '+421 949 881 334'
  ),
  (
    '15',
    'done',
    'van',
    'VW Crafter',
    'VW Crafter 2.0 TDI',
    'Diagnostika motora',
    'KI778VC',
    26.5,
    'Bytča',
    'WV1ZZZ2KZJX123456',
    '2.0 l',
    '103 kW',
    'Diesel',
    2019,
    '2.0 TDI',
    'FWD',
    'Dodávka',
    4,
    156700,
    'Automatická',
    'Občas sa rozsvieti kontrolka motora, auto občas prepne do núdzového režimu.',
    'Silvia Hrušková',
    '+421 918 772 119'
  ),
  (
    '16',
    'inquiry',
    'van',
    'Renault Master',
    'Renault Master 2.3 dCi',
    'Servis klimatizácie',
    'TN904RM',
    58.7,
    'Ružomberok',
    'VF1MA0000H1234567',
    '2.3 l',
    '96 kW',
    'Diesel',
    2017,
    '2.3 dCi',
    'FWD',
    'Dodávka',
    4,
    241300,
    'Manuálna',
    'Klimatizácia nefúka dostatočne studený vzduch, prosím o kontrolu a doplnenie chladiva.',
    'Dušan Poliak',
    '+421 905 663 778'
  )
on conflict (id) do nothing;
