-- Supabase schema for cAsker sidebar requests
-- Run this file BEFORE appointments.sql migrations.
create table if not exists public.requests (
  id text primary key,
  status text not null default 'inquiry' check (status in ('inquiry', 'waiting', 'done', 'completed')),
  vehicle_category text not null default 'car' check (vehicle_category in ('car', 'van')),
  vehicle_name text not null,
  vehicle_title text not null,
  service text not null,
  license_plate text not null,
  distance_km numeric(8, 1) not null,
  location_city text not null,
  vin text not null,
  engine_volume text not null,
  power text not null,
  fuel_type text not null,
  year integer not null,
  engine text not null,
  drive text not null,
  body_type text not null,
  doors integer not null,
  mileage_km integer not null,
  transmission text not null,
  inquiry_description text not null,
  user_name text not null,
  phone text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists requests_vehicle_category_idx on public.requests (vehicle_category);

create index if not exists requests_status_idx on public.requests (status);

alter table public.requests enable row level security;

create policy "Allow anon read requests"
  on public.requests
  for select
  to anon
  using (true);

drop policy if exists "Allow anon update request status" on public.requests;

create policy "Allow anon update request status"
  on public.requests
  for update
  to anon
  using (true)
  with check (status in ('inquiry', 'waiting', 'done', 'completed'));

drop policy if exists "Allow anon insert requests" on public.requests;

create policy "Allow anon insert requests"
  on public.requests
  for insert
  to anon
  with check (true);

insert into public.requests (
  id,
  status,
  vehicle_category,
  vehicle_name,
  vehicle_title,
  service,
  license_plate,
  distance_km,
  location_city,
  vin,
  engine_volume,
  power,
  fuel_type,
  year,
  engine,
  drive,
  body_type,
  doors,
  mileage_km,
  transmission,
  inquiry_description,
  user_name,
  phone
) values
  (
    '1',
    'inquiry',
    'car',
    'Škoda Octavia',
    'Škoda Octavia 2.0 TSI',
    'Výmena oleja + filtrov',
    'AA970VG',
    13.4,
    'Bytča',
    'TMBBS21Z802123456',
    '1.9 l',
    '77 kW',
    'Diesel',
    2004,
    '2.0 TSI',
    'FWD',
    'Combi',
    5,
    173651,
    'Manuálna',
    'Potrebujem skontrolovať vozidlo, či je na ňom bezpečne jazdiť do doby opravy.',
    'Ján Novák',
    '+421 905 123 456'
  ),
  (
    '2',
    'done',
    'car',
    'VW Golf',
    'VW Golf 1.4 TSI',
    'Diagnostika motora',
    'ZA123AB',
    8.2,
    'Žilina',
    'WVWZZZ1KZ6W386752',
    '1.4 l',
    '90 kW',
    'Benzín',
    2016,
    '1.4 TSI',
    'FWD',
    'Hatchback',
    5,
    98420,
    'Automatická',
    'Motor občas cuká pri studenom štarte, chcem vedieť príčinu a odhad opravy.',
    'Mária Kováčová',
    '+421 911 987 654'
  ),
  (
    '3',
    'done',
    'car',
    'Ford Focus',
    'Ford Focus 1.6 Ti-VCT',
    'Výmena brzdových doštičiek',
    'BL456CD',
    21.7,
    'Martin',
    'WF0AXXWPMA1234567',
    '1.6 l',
    '85 kW',
    'Benzín',
    2012,
    '1.6 Ti-VCT',
    'FWD',
    'Combi',
    5,
    142300,
    'Manuálna',
    'Pískanie pri brzdení, prosím o kontrolu a výmenu doštičiek.',
    'Peter Horváth',
    '+421 948 222 333'
  ),
  (
    '4',
    'inquiry',
    'car',
    'BMW 320d',
    'BMW 320d xDrive',
    'Kontrola klimatizácie',
    'TN789EF',
    142.5,
    'Poprad',
    'WBA8E310X0A123456',
    '2.0 l',
    '140 kW',
    'Diesel',
    2018,
    '2.0 d',
    '4x4',
    'Sedan',
    4,
    86500,
    'Automatická',
    'Klimatizácia nechladí dostatočne, prosím o diagnostiku a servis.',
    'Eva Bartošová',
    '+421 903 444 555'
  ),
  (
    '5',
    'inquiry',
    'car',
    'Audi A4',
    'Audi A4 2.0 TDI',
    'Kontrola bŕzd',
    'KI111XX',
    45.3,
    'Kysucké Nové Mesto',
    'WAUZZZ8K9KA123456',
    '2.0 l',
    '110 kW',
    'Diesel',
    2015,
    '2.0 TDI',
    'FWD',
    'Sedan',
    4,
    198400,
    'Manuálna',
    'Pri brzdení cítim vibrácie, prosím o kontrolu kotúčov a doštičiek.',
    'Tomáš Varga',
    '+421 907 111 222'
  ),
  (
    '6',
    'inquiry',
    'car',
    'Toyota Corolla',
    'Toyota Corolla 1.8 Hybrid',
    'Servis hybridného systému',
    'ZA456CD',
    22.8,
    'Rajec',
    'JTNKARJE0J1234567',
    '1.8 l',
    '90 kW',
    'Hybrid',
    2019,
    '1.8 Hybrid',
    'FWD',
    'Hatchback',
    5,
    75600,
    'Automatická',
    'Bliká kontrolka hybridného systému, potrebujem diagnostiku.',
    'Lucia Poláková',
    '+421 918 333 444'
  ),
  (
    '7',
    'inquiry',
    'car',
    'Peugeot 308',
    'Peugeot 308 1.6 HDI',
    'Výmena rozvodov',
    'NO789GH',
    68.9,
    'Námestovo',
    'VF3LB9HXBFS123456',
    '1.6 l',
    '68 kW',
    'Diesel',
    2011,
    '1.6 HDI',
    'FWD',
    'Combi',
    5,
    231500,
    'Manuálna',
    'Po studenom štarte počujem rattle, chcem skontrolovať rozvody.',
    'Michal Kollár',
    '+421 949 555 666'
  ),
  (
    '8',
    'inquiry',
    'car',
    'Honda Civic',
    'Honda Civic 1.5 VTEC Turbo',
    'Geometria kolies',
    'ZA852MK',
    11.2,
    'Teplička nad Váhom',
    'SHHFK1760HU123456',
    '1.5 l',
    '134 kW',
    'Benzín',
    2020,
    '1.5 VTEC Turbo',
    'FWD',
    'Hatchback',
    5,
    62400,
    'Manuálna',
    'Auto ťahá doprava, potrebujem nastaviť geometriu a skontrolovať pneumatiky.',
    'Kristína Hudáková',
    '+421 910 222 118'
  ),
  (
    '9',
    'inquiry',
    'car',
    'Mercedes-Benz C 220',
    'Mercedes-Benz C 220 d',
    'Servis AdBlue',
    'TN334RS',
    96.4,
    'Liptovský Mikuláš',
    'WDD2050141A123456',
    '2.0 l',
    '125 kW',
    'Diesel',
    2017,
    '2.0 d',
    'RWD',
    'Sedan',
    4,
    118900,
    'Automatická',
    'Svieti kontrolka AdBlue, prosím o doplnenie a kontrolu systému.',
    'Roman Slanina',
    '+421 905 778 901'
  ),
  (
    '10',
    'inquiry',
    'car',
    'Suzuki Vitara',
    'Suzuki Vitara 1.4 Boosterjet',
    'Výmena oleja a filtrov',
    'NO445TU',
    54.1,
    'Tvrdošín',
    'TSMLYEA1S00123456',
    '1.4 l',
    '103 kW',
    'Benzín',
    2021,
    '1.4 Boosterjet',
    '4x4',
    'SUV',
    5,
    38700,
    'Automatická',
    'Blíži sa servisná prehliadka, chcem výmenu oleja, filtra oleja a vzduchu.',
    'Zuzana Oravcová',
    '+421 917 654 321'
  ),
  (
    '11',
    'inquiry',
    'car',
    'Opel Astra',
    'Opel Astra 1.6 CDTI',
    'Diagnostika DPF',
    'KI992OP',
    31.6,
    'Čadca',
    'W0LBF5D99G1234567',
    '1.6 l',
    '81 kW',
    'Diesel',
    2014,
    '1.6 CDTI',
    'FWD',
    'Combi',
    5,
    167800,
    'Manuálna',
    'Auto ide do regenerácie príliš často, chcem skontrolovať DPF a snímače.',
    'Filip Gašpar',
    '+421 944 112 887'
  ),
  (
    '12',
    'inquiry',
    'car',
    'Mazda 3',
    'Mazda 3 2.0 Skyactiv-G',
    'Kontrola podvozku',
    'ZA771MZ',
    17.9,
    'Rosina',
    'JM1BPACM1K1234567',
    '2.0 l',
    '90 kW',
    'Benzín',
    2018,
    '2.0 Skyactiv-G',
    'FWD',
    'Hatchback',
    5,
    91200,
    'Manuálna',
    'Po prejazde nerovnosťou počujem klepanie vpredu, prosím o kontrolu silentblokov.',
    'Andrea Križanová',
    '+421 908 445 776'
  ),
  (
    '13',
    'inquiry',
    'van',
    'Ford Transit',
    'Ford Transit 2.0 TDCi',
    'Výmena oleja a filtrov',
    'ZA331DT',
    19.4,
    'Žilina',
    'WF0XXXTTGX1234567',
    '2.0 l',
    '96 kW',
    'Diesel',
    2018,
    '2.0 TDCi',
    'FWD',
    'Dodávka',
    4,
    214800,
    'Manuálna',
    'Potrebujem servisnú výmenu oleja a filtrov pred dlhšou trasou po Slovensku.',
    'Martin Ďurica',
    '+421 910 441 220'
  ),
  (
    '14',
    'inquiry',
    'van',
    'Mercedes Sprinter',
    'Mercedes Sprinter 316 CDI',
    'Kontrola bŕzd',
    'NO552SP',
    37.2,
    'Dolný Kubín',
    'WDB9066331S123456',
    '2.1 l',
    '120 kW',
    'Diesel',
    2016,
    '316 CDI',
    'RWD',
    'Dodávka',
    4,
    289400,
    'Manuálna',
    'Pri plnom zaťažení cítim slabšie brzdenie, prosím o kontrolu brzdového systému.',
    'Jozef Kmeť',
    '+421 949 881 334'
  ),
  (
    '15',
    'done',
    'van',
    'VW Crafter',
    'VW Crafter 2.0 TDI',
    'Diagnostika motora',
    'KI778VC',
    26.5,
    'Bytča',
    'WV1ZZZ2KZJX123456',
    '2.0 l',
    '103 kW',
    'Diesel',
    2019,
    '2.0 TDI',
    'FWD',
    'Dodávka',
    4,
    156700,
    'Automatická',
    'Občas sa rozsvieti kontrolka motora, auto občas prepne do núdzového režimu.',
    'Silvia Hrušková',
    '+421 918 772 119'
  ),
  (
    '16',
    'inquiry',
    'van',
    'Renault Master',
    'Renault Master 2.3 dCi',
    'Servis klimatizácie',
    'TN904RM',
    58.7,
    'Ružomberok',
    'VF1MA0000H1234567',
    '2.3 l',
    '96 kW',
    'Diesel',
    2017,
    '2.3 dCi',
    'FWD',
    'Dodávka',
    4,
    241300,
    'Manuálna',
    'Klimatizácia nefúka dostatočne studený vzduch, prosím o kontrolu a doplnenie chladiva.',
    'Dušan Poliak',
    '+421 905 663 778'
  )
on conflict (id) do nothing;

alter table public.requests replica identity full;

alter publication supabase_realtime add table public.requests;
