-- Demo dopyty: pneuservis (tire) a odťah (towing).
-- Odťahové dopyty majú request_category = 'towing' → v dashboarde červená značka na mape.
-- Pred spustením: add-request-category.sql

insert into public.requests (
  id,
  status,
  request_category,
  vehicle_category,
  vehicle_name,
  vehicle_title,
  service,
  license_plate,
  distance_km,
  location_city,
  vin,
  engine_volume,
  power,
  fuel_type,
  year,
  engine,
  drive,
  body_type,
  doors,
  mileage_km,
  transmission,
  inquiry_description,
  user_name,
  phone
) values
  (
    '17',
    'inquiry',
    'tire',
    'car',
    'Hyundai i30',
    'Hyundai i30 1.6 CRDi',
    'Výmena letných pneumatík',
    'ZA552TP',
    11.3,
    'Žilina',
    'TMAH251CAL1234567',
    '1.6 l',
    '81 kW',
    'Diesel',
    2018,
    '1.6 CRDi',
    'FWD',
    'Hatchback',
    5,
    118400,
    'Manuálna',
    'Potrebujem prehodiť zimné na letné pneumatiky vrátane vyváženia kolies.',
    'Lucia Bartošová',
    '+421 907 441 220'
  ),
  (
    '18',
    'inquiry',
    'towing',
    'car',
    'Opel Astra',
    'Opel Astra 1.4 Turbo',
    'Odťah vozidla',
    'BL118OD',
    34.2,
    'Martin',
    'W0LPD6ECXG1234567',
    '1.4 l',
    '103 kW',
    'Benzín',
    2015,
    '1.4 Turbo',
    'FWD',
    'Combi',
    5,
    167800,
    'Manuálna',
    'Vozidlo neštartuje po nehode, potrebujem odťah do servisu v Martine.',
    'Tomáš Vlk',
    '+421 944 118 900'
  ),
  (
    '19',
    'inquiry',
    'tire',
    'car',
    'Kia Ceed',
    'Kia Ceed 1.0 T-GDI',
    'Prezutie a vyváženie',
    'ZA901PN',
    6.8,
    'Bytča',
    'U5YH3511AKL123456',
    '1.0 l',
    '74 kW',
    'Benzín',
    2020,
    '1.0 T-GDI',
    'FWD',
    'Hatchback',
    5,
    54200,
    'Manuálna',
    'Mám vlastné pneumatiky, potrebujem len prezutie a vyváženie všetkých kolies.',
    'Erik Baláž',
    '+421 911 220 331'
  ),
  (
    '20',
    'inquiry',
    'tire',
    'car',
    'Volkswagen Passat',
    'VW Passat 2.0 TDI',
    'Uskladnenie pneumatík + prezutie',
    'KI220PN',
    14.6,
    'Rajec',
    'WVWZZZ3CZJE123456',
    '2.0 l',
    '110 kW',
    'Diesel',
    2017,
    '2.0 TDI',
    'FWD',
    'Combi',
    5,
    198300,
    'Automatická',
    'Prezutie na zimné, staré uskladniť u vás do jari.',
    'Jana Šimková',
    '+421 948 771 002'
  ),
  (
    '21',
    'inquiry',
    'towing',
    'car',
    'Škoda Fabia',
    'Škoda Fabia 1.2 HTP',
    'Odťahová služba',
    'ZA881OT',
    4.2,
    'Bytča',
    'TMBBS25J203123456',
    '1.2 l',
    '47 kW',
    'Benzín',
    2008,
    '1.2 HTP',
    'FWD',
    'Hatchback',
    5,
    201400,
    'Manuálna',
    'Auto zostalo na križovatke, nejazdí. Potrebujem odťah do servisu v Bytči.',
    'Marek Ondruš',
    '+421 905 118 440'
  ),
  (
    '22',
    'inquiry',
    'towing',
    'car',
    'BMW X3',
    'BMW X3 xDrive20d',
    'Odťah po poruche',
    'ZA334OT',
    12.5,
    'Žilina',
    'WBAWZ5C50DD123456',
    '2.0 l',
    '140 kW',
    'Diesel',
    2016,
    '2.0 d',
    '4x4',
    'SUV',
    5,
    142600,
    'Automatická',
    'Zhasol motor na diaľnici pri Žiline, vozidlo je mimo cesty. Prosím o odťah.',
    'Iveta Krajčírová',
    '+421 918 660 118'
  ),
  (
    '23',
    'inquiry',
    'towing',
    'car',
    'Ford Ranger',
    'Ford Ranger 2.2 TDCi',
    'Odťah pick-upu',
    'NO559OT',
    28.4,
    'Čadca',
    'WF0FXXTACF1234567',
    '2.2 l',
    '92 kW',
    'Diesel',
    2014,
    '2.2 TDCi',
    '4x4',
    'Pick-up',
    4,
    256900,
    'Manuálna',
    'Poškodený predok po zrážke, auto nejazdí. Odťah do najbližšieho servisu.',
    'Róbert Jančo',
    '+421 944 902 771'
  )
on conflict (id) do update set
  status = excluded.status,
  request_category = excluded.request_category,
  vehicle_category = excluded.vehicle_category,
  vehicle_name = excluded.vehicle_name,
  vehicle_title = excluded.vehicle_title,
  service = excluded.service,
  license_plate = excluded.license_plate,
  distance_km = excluded.distance_km,
  location_city = excluded.location_city,
  vin = excluded.vin,
  engine_volume = excluded.engine_volume,
  power = excluded.power,
  fuel_type = excluded.fuel_type,
  year = excluded.year,
  engine = excluded.engine,
  drive = excluded.drive,
  body_type = excluded.body_type,
  doors = excluded.doors,
  mileage_km = excluded.mileage_km,
  transmission = excluded.transmission,
  inquiry_description = excluded.inquiry_description,
  user_name = excluded.user_name,
  phone = excluded.phone,
  updated_at = now();
